### ISSUE TITLE
Please provide an example folder illustrating how to override the default parameters for spring-data-redis

### ISSUE THREAD

**Issue by Trii** [spring-projects/spring-data-examples#396]
I am just starting out with spring-data-redis using lettuce and I can't seem to get the autowired objects to pick up `spring.redis.host` from my application.yml.

```yaml
spring:
  redis:
    host: xxxxxxxxxxx.cache.amazonaws.com
    port: 6379
```
Could you give me some pointers based off [example/springdata/redis/repositories/ApplicationConfiguration.java](https://github.com/spring-projects/spring-data-examples/blob/master/redis/repositories/src/main/java/example/springdata/redis/repositories/ApplicationConfiguration.java#L35)?
